os: linux
dist: xenial
services:
  - docker

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install: 'pip install -e .[test]'

script:
  - flake8
  - pytest -v --cov

after_success:
  - codecov

jobs:
  include:
    - stage: Docker integration test
      python: '3.8'
      script: pytest -v -m docker

    - stage: Local integration test
      python: '3.8'
      script: pytest -v -m local
